### ISSUE TITLE
A query

### ISSUE THREAD

**Issue by Dominic3243** [umbrellaplug/umbrellaplug.github.io#107]
Hi
I am a relatively new user and found umbrella addon wonderful. 
Usually i play tv show episodes from trakt progress;my doubt is on clicking an episode on progress list it shows all the episodes menu of that season/series.Can umbrella play the video directly on clicking an episode on my trakt progress rather than displaying all episodes?? 

On enabling direct progress scraping;after a particular episode it is playing the next episode of another tv show in my  trakt progress rather than the next episode of the series.. 

If it is a feature of umbrella addon my apologies.. Hope my doubt is understandable..Thanks once again for maintaining this addon

Regards

**Comment by umbrellaplug** [comment]
Direct progress scraping and playnext don't mix at all. You'll have to use one or the other. It sounds like you may be able to accomplish what you're looking for by turning off Direct progress scraping. Enabling playnext and when you go to play an episode instead of clicking, hold down on the item in your widget till you get the context menu and select "play from here". I'm thinking that will accomplish what you're looking for.

**Comment by Dominic3243** [comment]
Yaa.. Okk thanks.. Understood
