### ISSUE TITLE
No Stream available on specific tv show

### ISSUE THREAD

**Issue by jaimsitecom** [umbrellaplug/umbrellaplug.github.io#129]
Is this a Cocoscraper issue instead?  I had BLEACH THOUSAND YEAR BLOOD WAR inserted into my kodi library via umbrella. But when i try to play an episode, it couldn’t find a stream even if it’s already been shared via major torrent sites like 1337x, GLODLS, Piratebay, Magnetdl and others. I just find it strange why during scraping for the episode, it won’t hook up with a single stream, even tho the episode is already available.

please close if this isn’t an umbrella issue. Just wondering why it couldn’t find a stream. 

Thanks in advance.

**Comment by umbrellaplug** [comment]
This is a common issue we have with Anime. Unfortunately, the people uploading anime refuse to follow any consistent upload format.
When we look for a torrent or file we look for SxEx. This file as an example I found on Bitsearch was labeled like this:
[Anime Time] Bleach Thousand-Year Blood War - 08 [1080p][HEVC 10bit x265][AAC][Multi Sub].mkv

Scrapers would not return that ever because of the naming convention used. If it was S2E8 or S02E08 we would pick it up, but we cannot like that. You are better off using Otaku for anime as they are able to make more changes to scraping and those types of things for anime exclusive searches.

**Comment by jaimsitecom** [comment]
Got this. Ty again!
