### ISSUE TITLE
Items added from Umbrella to Kodi library do not trigger Umbrella source selection

### ISSUE THREAD

**Issue by fr1sty** [umbrellaplug/umbrellaplug.github.io#140]
I don't know if this is related with the problems Trakt has at this moment. But when I add a movie from within Umbrella to the Kodi library. It shows up in my library, but when I click it it triggers TMDb helper in stead of the Umbrella source selection screen. 
Adding and running movies from favorites is still working. 

Running version 6.5.97 from the test repository. Tried to install version 6.5.95 from the normal repository but got installation failed. Probably need to remove things manual before being able going back from test to normal version.

**Comment by umbrellaplug** [comment]
Can you double check your settings and see if you have "create tmdbhelper strm" checked on your library settings in umbrella?

Yeah, I'm sorry about that one. Switching from a test version back to regular may be a pain this once due to me switching from 3 digit numbers back to 2 for versions. I got the same issue. I was able to reboot kodi and install from repo by selecting "versions" on the addon and selecting the official repo version. It did take a reboot of kodi though.

**Comment by fr1sty** [comment]
Yes the create tmdbhelper strm is checked, and I can see the files on the disk. 

Uninstalled, kept settings, rebooted and now successfully installed the normal version. 
Added another movie to my library, but still no Umbrella source selection coming up. Only the TMDb helper selection youtube,etc

**Comment by umbrellaplug** [comment]
Yeah, that's working as expected. When you have that setting checked and you add an item to library the strm file that is created is created to call tmdb instead of umbrella. You can set TMDBHelper to call umbrella source select and that would work, but with that setting turned on any file brought into the library will have a strm file created with the url pointing to tmdbhelper instead of umbrella.

**Comment by fr1sty** [comment]
Yes unchecking it solved the problem! Funny thing is that I always had it checked.
