### ISSUE TITLE
Unable to play files from Real Debrid

### ISSUE THREAD

**Issue by kenta210** [umbrellaplug/umbrellaplug.github.io#167]
https://user-images.githubusercontent.com/120475575/210125018-2a865a2c-025e-4d48-a05e-a0fe0f41c45f.mp4

Log: https://paste.kodi.tv/cuxuqowayi.kodi

**Comment by umbrellaplug** [comment]
This will be fixed in the next update. Some imports were missing for some logging.

I just posted a new version on the test repo. You're welcomed to try that one and let me know if it makes a difference. The test repo can be added by adding https://umbrellaplug.github.io/umbrellatest as a source and loading version 6.6.02.

Let me know if you get a chance to try that out and your results.

**Comment by kenta210** [comment]
Version 6.6.02 works. Thankyou. Appreciate ur work :)

**Comment by xyzfre** [comment]
When installing this test version when you released the official is there anything we have to do on our end

**Comment by umbrellaplug** [comment]
> When installing this test version when you released the official is there anything we have to do on our end

Nothing special. You will not get an alert when the official is updated till it is updated to a higher version than your test version. Test versions still check the main repo for version numbers when checking for updates. I'll be pushing this version today, but 6.6.03 isn't far behind it with updates for some lists so you should see an update alert when that one hits.

Short answer: Nah, you'll get an update alert once the main repo goes past this version.
