### ISSUE TITLE
[BUG] Trakt Sync Issue

### ISSUE THREAD

**Issue by leemacca13** [umbrellaplug/umbrellaplug.github.io#172]
Sorry to bother you again, over Christmas I decided to move to using the arctic horizon 2 skin. And have a widget setup from umbrella progress everything is working fine. Apart from now that shows are returning from their Christmas break, they are not showing up in my progress list and the only way to get them to appear is to force a sync with trakt. I've tried reauthorising but seems to have made no difference. I also use my own trakt api keys but have done previously without an issue

**Comment by leemacca13** [comment]
Sorry I should also add even if I go into the addon itself and go into progress the shows still do not appear until I force a sync with trakt.

**Comment by umbrellaplug** [comment]
Hey, you opened a blank issue to report a bug. Please use the bug templates when reporting bugs. It helps me keep track of what is a request and what is a bug when looking at priority for working on things. 

I have checked on multiple systems this morning and progress appears to be working as expected. (shows we watched last night now show the next episode in progress)

I'm going to change this to a "bug report" instead of blank issue. Can you provide logs?

**Comment by leemacca13** [comment]
Apologies I will make sure I do that from now on. Sorry just to clarify any shows I've been watching the progress works fine, it's shows that I've watched all the current episodes and then that show has a new episode out yesterday or today. It's those episodes that are not appearing. So for example a show that I have watched all the available episodes for had a new episode released at 1am uk time but when I checked this morning the show didn't appear on my progress list until I forced a sync with trakt. 

I have attached a log as requested, apologies again. 

https://paste.kodi.tv/quqefajeyo

**Comment by umbrellaplug** [comment]
Thanks! I think you may be hitting the cache. Whenever you load the progress list it checks the internal cache and looks if it's been 12 hours since the last time it checked it. If it hasn't then it uses the list stored in memory. If it's been more than 12 hours since it last loaded the list it clears it from memory and loads it fresh. Keep it mind it's looking at 12 hours from the last time it pulled the list, not 12 hours from the last time you opened the list. Next time this happens to you, can you try just clearing cache instead of the full trakt sync and see if that makes the list update for you? If clearing cache makes the list update without forcing a sync from Trakt that will tell me if it's a bug or just being saved to cache.

**Comment by leemacca13** [comment]
Ah I see thank you, yeah I will give that a try tomorrow as there is quite a few shows that should be returning overnight. So I will have a look tomorrow and let you know. Thanks again.

**Comment by umbrellaplug** [comment]
Let me know your results.

It is planned in the future to allow for users to set the cache time on each lists themselves in the settings.

**Comment by leemacca13** [comment]
Hi just to let you know that I ran into the same problem again with shows now showing up in progress. So I went into the addon and cleared the cache and reloaded the skin and that made the shows appear.

**Comment by umbrellaplug** [comment]
Yeah. So that's just cache on the list. That's working as expected. 

Bad news is that needs to stay that way. That's how we minimize the amount of calls we make to trakt and other places api to keep traffic reasonable. 

Good news is I plan on making that controlled by the user soon. I will he adding controls in to allow you to change the amount of hours lists are kept in cache. I don't like it, but I'll add an option to use 0 hours for no cache.

Pulling lists fresh versus from cache does take longer though so be aware you may see a speed difference if not set to cache.

**Comment by leemacca13** [comment]
That's ok not a problem, thank you for looking into it for me. Ah ok thank you tbh the least I'd set it for is probably 6-7 hours as don't wanna be causing unnecessary traffic.
