### ISSUE TITLE
Tv  Show will not resume with tmdb helper

### ISSUE THREAD

**Issue by Dappakid13** [umbrellaplug/umbrellaplug.github.io#225]
### Bug

I have noticed for over a month a bug with umbrella, when I use umbrella as a player I am not able to resume my finish watching (scrobble resume points). I did some testing with movie as well and the movie work just fine.

### Expected Result

It should pick up my resume points where I last left the episodes.

### Steps To Reproduce

Open kodi.
point widget/go to tmdb tv shows--> in progress episode.
Select a episode.
Episode starts over instead of resuming.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Using kodi nexus 20.0
Nvidia Shield, 4k firestick, formuler z10

[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10728958/kodi.log)

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by Dappakid13** [comment]
I actually have the latest version 6.6.15. I updated it last night before doing the test, I can remove the old context menu but it is the same

**Comment by umbrellaplug** [comment]
Sorry, but this is not related to Umbrella. It looks like you likely need an update or something on TMDB Helper or something else. The reason I keep suggesting updating is due to this in the logs:

```
2023-02-13 23:48:18.158 T:23229 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-02-13 23:48:18.169 T:23229 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint
```

There was a change in the way listitem properties were assigned in Kodi 20. All of the code in Umbrella has been changed on the latest versions to not use setProperty on these items.

I'm seeing a large amount of errors with TMDBHelper as well in your logs.
```
2023-02-13 23:48:29.233 T:23890    info <general>: [plugin.video.themoviedb.helper]
                                                   CACHE: Locked: Retrying DB commit...
```
```

2023-02-13 23:48:17.347 T:23471    info <general>: [plugin.video.themoviedb.helper]
                                                   CACHE: _database ERROR ! -- 
```

I'd recommend checking with Jurial about it on his side or checking for latest version of tmdbhelper or reloading it completely. It appears to have some type of cache database lock going on from the logs. Good Luck!

**Comment by Dappakid13** [comment]
Thank you will do that
