### ISSUE TITLE
[BUG] "british" trakt lists search shows empty TV show lists

### ISSUE THREAD

**Issue by cg00001** [umbrellaplug/umbrellaplug.github.io#230]
### Bug

I did a "british" trakt lists search and while movie lists seem fine, show lists appear empty.
I did the same search on TMDbH and it gives lists with content.
Don't know if it's me.

### Expected Result

Working shows lists.

### Steps To Reproduce

Go to Trakt lists search, type british and look in TV shows lists.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi Nexus

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I was able to find content on multiple lists when searching "british" as described. I did see that several of the lists are returned on tv shows, but actually do not have any tv shows on the list due to being listed with trakt as a mixed content list. This may be what you're seeing since the list would show up under tv shows, but wouldn't have anything on it. A couple examples I tried were:

british - leoaddo (empty)
british - houpsonfire (21 shows returned)
british - simiansays (37 shows returned)
