### ISSUE TITLE
[FEATURE] Possibility of using trakt for episode metadata

### ISSUE THREAD

**Issue by MrMeatballSub** [umbrellaplug/umbrellaplug.github.io#260]
### Feature

Would it be possible for this to be added?  I'll pay for the api, I don't think it's very expensive

**Comment by umbrellaplug** [comment]
The trakt api is free. It's already utilized for run times and other things within the addon. Changing meta to be pulled from trakt instead of tmdb is a huge job. It's not something I'm willing to do at this point. I do understand why the request is being made as some episodes appear differently on tmdb than on trakt for season and episode number. It's just not something I'm willing to take on currently. I will consider adding it as an option in the future though.

**Comment by MrMeatballSub** [comment]
I understand.  This is the only thing making me use seren over umbrella, despite umbrella being better in literally everything else.

Thanks hoping to see it in the future releases
