### ISSUE TITLE
Trakt Watched List[FEATURE] Short Description

### ISSUE THREAD

**Issue by FireStickKodi36** [umbrellaplug/umbrellaplug.github.io#273]
### Feature

Currently when Trakt Movie Watched List (History) is displayed it shows the duplicates (each time it's watched) it would be nice to sort the watched list in alphabetical order with the duplicates removed. (see EZRA addon navigation).

Thanks for your consideration.

**Comment by umbrellaplug** [comment]
I see the duplicates, those can be removed.
Sorting currently is done by the order that you watched them in because it's history. I will add an option into TV Shows section and General section to allow for sorting of the history list also. You can see the sorting options available already for other lists there.

> (see EZRA addon navigation)

No, see https://github.com/umbrellaplug/umbrellaplug.github.io#issues

**Comment by FireStickKodi36** [comment]
Thank you

**Comment by umbrellaplug** [comment]
Decided to leave the sorting alone. Duplicates have been removed in episodes and movies though.

**Comment by umbrellaplug** [comment]
Feature in latest update.

**Comment by FireStickKodi36** [comment]
Thanks for addressing the request.

Installed ver 6.6.26 but the duplicates are still showing. Do I need to change any settings to engage the change?

Just curious was the sort part of it too much of a headache?

Thanks again.

On Jul 26, 2023, at 11:01 AM, umbrellaplug ***@***.***> wrote:

﻿

Feature in latest update.
