### ISSUE TITLE
Pro Wrestling Scraper

### ISSUE THREAD

**Issue by wormyragtime** [umbrellaplug/umbrellaplug.github.io#28]
Hi,

Loving Umbrella so far. Venom was great up until recently when the Trakt issue started. Really happy you’ve fixed it and how you are so responsive to your community of users. 

Just want to ask if you could add Pro Wrestling to your scraper. Particularly AEW & WWE shows. Currently they have to be added manually using host links or magnet links. The Umbrella index shows all the episodes but the scrapers can’t find anything because the file formatting is different from Tmdb/Trakt. Would love the convenience of this so I wouldn’t have to add links manually 4 or 5 times a week. 

Great work so far and thank you!

**Comment by umbrellaplug** [comment]
Yeah, I can look into this. Do you mind sending me an example of something you're searching for that isn't yielding any results and then also where you are actually finding it from? It may be an adjustment to the scrapers or it may need to be an entirely new scraper added.

**Comment by wormyragtime** [comment]
Some examples of weekly shows: AEW Dynamite, AEW Rampage, WWE Raw, WWE Smackdown. If you go to search in Umbrella and type in AEW or WWE, you will see all of these shows in the results. Scraper finds nothing though.

They also do monthly or quarterly premium events/pay per view events. For example AEW All Out, AEW Double or Nothing, WWE Summerslam, WWE Wrestlemania, WWE Royal Rumble Umbrella cannot finds these in search results. 

Files for any of these can be found on your torent site of choice such as 1337. Just search for AEW Dynamite or WWE Raw. Filename formatting usually follows same structure for all of  the above shows. For example, AEW Dynamite DATE 1080p WEB x264 GROUP. 

Hope that helps. Let me know if you need anything else.

**Comment by wormyragtime** [comment]
I tried a filterless scrape from all providers, and a custom query from all providers. Still seeing no results. 

I have a guess that maybe the problem is the scraper is looking for Season # and episode #. For example for the July 6th episode of Dynamite, the scraper may be looking for S04E27. But wrestling episodes don’t use season and episode in the filename structure. They use the date only. For example, the filename will have 2022 07 06 or 6th July 2022. But it won’t have S04E27.

**Comment by umbrellaplug** [comment]
Yeah I see what you're saying, that sucks. Let me see if I can add something in for maybe a date and title search only.

**Comment by umbrellaplug** [comment]
I'm going to close this issue as I'm no longer maintaining the scrapers for this addon. Good luck, I hope you can find something that meets your needs for wrestling shows. Have a great one!

**Comment by wormyragtime** [comment]
You’re not maintaining the scrapers? How come? So that it’s for umbrella then? Dang, I really thought you were gonna do it for me lol.

**Comment by umbrellaplug** [comment]
Umbrella isn't going anywhere. I'm just now using cocoscrapers. The scrapers are maintained by a different developer so I can focus on the addon.

**Comment by wormyragtime** [comment]
Who is the developer of cocoscrapers? I’d like to ask this person about adding pro wrestling.

**Comment by 123Venom** [comment]
Why not use a dedicated wrestling addon?  I've heard `World of Wrestling` is good.  Due to the naming conversions of wrestling being so different than that of tvshows/episodes I don't think you'll have much luck getting addons to alter all their scrapers for the differences.  This is also why anime has dedicated addons because the naming used is unique.

**Comment by wormyragtime** [comment]
I like having the ability to choose my file from results, same as for tv shows and movies so I can watch the better audio/video quality files. Using a scraper or manually adding to  Debrid allows for this. I’m not sure if a dedicated wresting addon would have that ability. 

Tv shows use S01E01 for naming. Wrestling uses dates. That’s the only difference. I don’t see why there would be difficulty for a developer in making a scraper work with that. 

I understand devs do this free and it’s their time that goes into this. I would donate for their time to implement this.

**Comment by 123Venom** [comment]
I think I know what the differences are and didn't think I needed to spell it out.  The point is the scrapers would all need to change and good luck convincing them to do it.  If it's not that difficult why not fork the scrapers and modify them yourself?

**Comment by wormyragtime** [comment]
Because I am not a developer? I would not have asked, if I could do it myself. Not sure why you seem to be offended or upset. I certainly didn’t intend to do that.

**Comment by 123Venom** [comment]
Not upset in the least.  I gave you my opinion on it and you came back with trying to be smart about what the differences are and that it shouldn't be that difficult.  I love it when users think that way and they'll always get that response from me.  My original answer was solid and appears more like it was not accepted and good enough for you so you chose to push the issue.  Even being a developer I'd not touch this one.  I'd make a dedicated Wrestling addon tailored to the search query it needs and then the title checking methods required.  I just do not think an addon that's movies/shows are a fit for this. Could it be done? Yes but it would not be easy and be very time consuming and messy imo.

Have a nice day.

**Comment by wormyragtime** [comment]
I didn’t come back smart; you did. Which is why I thought that you were upset. I simply stated that I didn’t think it would difficult for a dev to implement. Just because you thought that my opinion on that is incorrect, doesn’t mean that I’m being smart with you. I wasn’t. Not sure what your problem is. 

If you don’t think this belongs in an addon for movies and shows; that’s your opinion. I disagree with you on that. It’s a tv show like the others. Just needs to be implemented. 

I’ll take your word for it that it would be difficult, time consuming and messy. 

In any event, I’m just here to ask the umbrella dev how I can contact the dev of coco scrapers.

**Comment by 123Venom** [comment]
You just can't help yourself but keep continuing on and on...lol

You can disagree all you want but come back and let us know when you find a dev interested in doing this and see who they agree with more. Seren, Fen, Umbrella...none of them are handling these differences and I know of no addon doing so, other than a dedicated wrestling addon.

Trust me the scraper dev already seen this and his answer is NO.

Good luck, I really do mean that.

**Comment by wormyragtime** [comment]
Look in the mirror 🤦‍♂️

**Comment by umbrellaplug** [comment]
@wormyragtime I don't know if you realized who you were going back and forth with here, but that was @123Venom. The original developer.

I'm not trying to be rude or jump into any back and forth here, but if he's saying it isn't easy to do with years more experience than me I'm going to take his word for it out of pure respect for the work he's done previously. 

I hope you find what you're looking for in an addon but it's not something the scraper developer is willing to work on at this time. I'm pretty sure it's for the same reason I just quoted to you. It just simply may not be all that easy to do and is more work than they or I am willing to take on right now. I believe Venom even quoted an addon in one of the comments for you that may better fit what you're looking for.

In the future, please don't go back and forth with Venom or anyone else in any of my issues. I really appreciate him taking his time to even look at this stuff and was unaware he was so I really don't want to discourage him from helping with anything if he's able to in the future due to bad interactions. I hope this is understandable and we can all stay respectful with each other.

**Comment by wormyragtime** [comment]
@umbrellaplug Perhaps you should direct that at him? He took something I said the wrong way and chose to escalate. I wasn’t disrespectful to him in anyway. I tried to de-escalate and he wasn’t having it. I understand that you want him to continue helping you, but expecting other people to kiss his ass and stroke his ego is not the way. 

I do appreciate your respectful responses to my questions though. You have been nothing but kind. Be well.

**Comment by 123Venom** [comment]
>but expecting other people to kiss his ass and stroke his ego is not the way.

Class act right there.  I did not speak this way to you.  There are different ways users chose to adsorb the info given to them and how they accept it as adults.  Take this one for example that occurred after this fiasco with you....

https://github.com/umbrellaplug/umbrellaplug.github.io/issues/50#issuecomment-1207307659

A True Gentleman!  He took the info I gave him and did not reply with attempting to educate me on coding as you attempted, a simple thumbs up said it all.  You'll prob read my response to him as me having an ego and my bet says he read my response as being helpful and giving him decent info to test out for himself, you just won't get it and that's 100% apparent.  I want you to approach all devs from now on with the same manner that you replied to me with, "it should not be that difficult".  Then you sat openly saying `Because I am not a developer` so how on earth could you know the answer you claimed to me that it should not be that difficult?  Do you seriously not hear how insane that is?

There's different types of users who posts issues.  There's those that take the info a dev gives to them and replies with, "I understand, and thank you for that information", or even a simple thumbs up to thank them for their time.  While other can not accept the facts and chose to argue it thinking maybe if they push the issue they'll get their way.  You were captain obvious in your endeavor of which type of user you were.

I'll promise you this though after your last insult.  I'll make it my mission that not one of your requests makes it into the scrapers...guess why?  Because I write them smart boy.

**Comment by wormyragtime** [comment]
You didn’t, huh? Okay. You’re a real special one. I never attempted to educate you on coding. You twisted my words to pick a fight. Now you’re here posting examples of how you expect to be spoken to. Amazing. 🤣And you’re telling me you don’t have a massive ego? Something I said upset you, though you couldn’t admit it. If you can’t speak to someone like an adult(like umbrelladev does), don’t expect a user to treat you like one. It goes both ways buttercup. Poor guy.

**Comment by umbrellaplug** [comment]
Had enough of this. Blocked.
