### ISSUE TITLE
[BUG] After latest release text is invisible - colors incorrect

### ISSUE THREAD

**Issue by endlessterror** [umbrellaplug/umbrellaplug.github.io#302]
### Bug

I've got a couple of LibreELEC-stable boxes (one Intel-based, one Odroid C2), both running LibreELEC 11 (Kodi 20). Up to the previous umbrella version everything worked like a charm. Kodi skin is the default.

After the latest update, the searching for sources (the one with the umbrella animation) was not showing some text or was simply illegible, due to the dark-fonts-on-dark-background suddenly used. I've went to the umbrella general settings and pressed defaults/reset to bring whatever umbrella thinks might be a proper color setup, but things only became worse. This happened on both boxes.

I'm attaching two photos: one that shows the result for real-debrid item and the second that shows the trakt authenticate dialog, which should display the code that I should enter on trakt.tv. As you can see, the code is not visible at all.

EDIT: Checking umbrella.log errors and specifically references to "invalid literal for int...", could this be a locale problem? My LibreELEC/Kodi setup is set to Greek.

### Expected Result

1. Search for sources
2. Colors are wrong; umbrella progress dialog/RD results/everything except the addon main menus are not displayed properly and are impossible to understand what you see.

### Steps To Reproduce

1. Should be self-explanatory from above.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

LibreELEC 11 (Kodi 20). PC 64-bit and Odroid C2.
![20230728_142205](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8733010/95cf3140-dc41-4900-a5df-9b455a3bbffc)
![20230728_142016](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8733010/1964a730-d81d-4f54-bc8a-a55e96fe5570)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Seems to be related to libreelec not recognizing the kodi 20 "colorbutton" setting. Not 100% sure I want to roll an update back for one type of system. I'll see what I can do. The matrix version should work and have all the old colors but only why it would work for you currently is to install from zip as repo is going to point you to the version for your system.

**Comment by endlessterror** [comment]
I understand. And thanks for an awesome addon too!

Can you please provide a link for the zip I should download (not sure which is the matrix version )?

Do I simply uninstall the current and the repo a f just install the zip?

**Comment by Omarscomin** [comment]
> Seems to be related to libreelec not recognizing the kodi 20 "colorbutton" setting. Not 100% sure I want to roll an update back for one type of system. I'll see what I can do. The matrix version should work and have all the old colors but only why it would work for you currently is to install from zip as repo is going to point you to the version for your system. 

Is is possible that this issue is skin related? I saw that a few others reported this same problem on Reddit yesterday, and I believe all of them were using Arctic Zephyr. I'm running 20.2 with Arctic Horizon 2 on a Nvidia Shield Pro and a 2nd generation Fire Cube, and I haven't run into any issues yet.

**Comment by umbrellaplug** [comment]
Yes. I Can attach a zip for you. It will take me a little bit as I'm not near pc currently. I will add it here as soon as I can. Can you post the log so I can see the invalid int error. 

Are you using a skin? If you are, can you try switching to default and setting colors?

I'm currently on vacation but I've got a little time in the mornings to look at stuff.

**Comment by umbrellaplug** [comment]
> > Seems to be related to libreelec not recognizing the kodi 20 "colorbutton" setting. Not 100% sure I want to roll an update back for one type of system. I'll see what I can do. The matrix version should work and have all the old colors but only why it would work for you currently is to install from zip as repo is going to point you to the version for your system. 
> 
> Is is possible that this issue is skin related? I saw that a few others reported this same problem on Reddit yesterday, and I believe all of them were using Arctic Zephyr. I'm running 20.2 with Arctic Horizon 2 on a Nvidia Shield Pro and a 2nd generation Fire Cube, and I haven't run into any issues yet. 

It's absolutely possible. That's actually one of the things I was asking about in my last reply.

**Comment by umbrellaplug** [comment]
https://raw.githubusercontent.com/umbrellaplug/umbrellaplug.github.io/master/matrix/zips/plugin.video.umbrella/plugin.video.umbrella-6.6.26.zip

**Comment by umbrellaplug** [comment]
From the log it looks like in one of my functions comparing for a dark color or light color it's coming in as a blank color. I'll need to track down where that's happening once I'm back to a place to really look into this. I've added a simple catch in the color compare for now that should work around this for in the mean time. If no color is passed in it should return "dark" now by default to give you some lighter text on those popups. If you get a chance can you try the latest test version on the test repo. I also attached a zip with the matrix version of 6.6.26 for you that still has the older color options in it. Let me know how this works out for you. I should be able to get back to my Pi4 and librelec next week to find where the blank color value is coming from.

https://umbrellaplug.github.io/umbrellatest

Should be version 6.6.261.

**Comment by umbrellaplug** [comment]
> Don't spoil your personal time for this mate :) You're doing this for free, so I'm more obliged and thankful that you can imagine ;)

![IMG_2972](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/107957815/468bb082-a884-48ee-b8ae-268de2144a3c)

No worries... Not a bad work environment. :)

**Comment by endlessterror** [comment]
> From the log it looks like in one of my functions comparing for a dark color or light color it's coming in as a blank color. I'll need to track down where that's happening once I'm back to a place to really look into this. I've added a simple catch in the color compare for now that should work around this for in the mean time. If no color is passed in it should return "dark" now by default to give you some lighter text on those popups. If you get a chance can you try the latest test version on the test repo. I also attached a zip with the matrix version of 6.6.26 for you that still has the older color options in it. Let me know how this works out for you. I should be able to get back to my Pi4 and librelec next week to find where the blank color value is coming from.

Test version looking okay:
* the umbrella animation text appeared just fine
* the total sources display also came up but the gold "1080p" logos are now red (lotsa red), as well as the 720p logos. I understand that is a quick fix, but nevertheless I'm attaching a screenshot from the test build. 

No errors/warnings now in the umbrella.log.
![20230728_181440](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8733010/7d0f33bb-cd4a-43cd-94ff-3484f4c55bea)

Thank you!

> No worries... Not a bad work environment. :)

Looks nice indeed! :)

**Comment by umbrellaplug** [comment]
Should be any to change that red from settings. Look for real debrid under sources and you can set to a new color. You can also change the settings from provider colors to single highlight. Whatever works for you.

**Comment by endlessterror** [comment]
> Should be able to change that red from settings. Look for real debrid under sources and you can set to a new color. You can also change the settings from provider colors to single highlight. Whatever works for you.

Nah, got comfy with it already. ;)

I presume that moving this fix to the stable Kodi 20 branch is doable at some point, right?

**Comment by umbrellaplug** [comment]
I'll push it over to public release side later this evening. Please let me know if you run into any issue in the meantime. I'll push it as version 6.6.27 later if no issues come up.

**Comment by endlessterror** [comment]
> I'll push it over to public release side later this evening. Please let me know if you run into any issue in the meantime. I'll push it as version 6.6.27 later if no issues come up.

Will be more than happy to report any findings. If you wish you can close this issue right now. Or after I install the newer stable one.

I'll pop up another minor issue which is inexplicable right now, low priority this one.

**Comment by DJMix-I-Can** [comment]
Hello... Not sure if it's related but thought I'd mention it.  After updating it to 6.6.26, I no longer have the option to change the colors because it's not showing. Under General, I should have the "Highlight Color, Movie Theatrical Unreleased Color, Titlebar Color & Button Color" &, under TV Shows, "Unaired Season/Episode Color" & under Source Options, "Scraper Dialog Highlight Color". With 6.6.26 it doesn't show. I checked your changes on Github & saw the following added in the control.py file, "if getKodiVersion()>=20:" BTW Since I'm still trying to learn Python, I noticed that line 433 in that python file isn't the same as your others which is "if getKodiVersion() > =20:" It has no spaces, not sure if it affects it. Anywho, I changed it with the spaces and that didn't help. I also thought maybe it was looking for an official Kodi installation. I'm using the Kodi Nerds version. I tested it with an official Kodi installation & still have the same issue. I then switched to the default skin & the color settings appeared. I now know that it has something to do with the skin. The 6.6.25 version showed it on all of my devices. Two Nividia shields & a windows laptop. Once I updated each device, all of them had the same issue. I have multiple builds with different skins that I play with. The following skins have this issue. Aura Mod V.1.1.9, Arctic Zephyr 2 Resurrection v1.0.3, Arctic Zephyr Reloaded v2.0.2 & my modified Arctic Zephyr 2 0.9.63.1 version. The only that worked was Arctic Horizon 2 v0.8.26. I recorded a video on a fresh installation with Arctic Zephyr Reloaded with just Umbrella 6.6.26 installed to show you what I mean. I checked the debug kodi & umbrella log file but don't see anything. I was able to make the changes using the default skin & then revert back to my other skin. The color changes did stick. I should also add,  I cleared the cache within Umbrella & Kodi. I also deleted umbrellas setting.xml file under userdata. I tried using my backup settings.xml file from 6.6.25 but that didn't work.  It's not urgent & have already changed the colors. Thought I'd mention it before it slips my mind. In all honesty, I'm surprised no one else has mentioned it. Anywho... Enjoy your vacation & thanks. Here goes that [video....](https://drive.google.com/file/d/1EynDv2rJ2AsLYzjPtwlilb2WbPSZpIx_/view?usp=drive_link).

**Comment by Omarscomin** [comment]
> In all honesty, I'm surprised no one else has mentioned it.


Isn't this entire thread about the issue that you're describing though?😅

**Comment by endlessterror** [comment]
Just reporting that after watching a couple of episodes with the test build I've not encountered this issue.

**Comment by DJMix-I-Can** [comment]
> > In all honesty, I'm surprised no one else has mentioned it.
> 
> Isn't this entire thread about the issue that you're describing though?😅

No, OP wasn't able to see the lettering. I was but the color options under the settings is not there. On reddit, users were saying the same BUT were not answering what skin they were using or if they tried the default skin.

**Comment by Omarscomin** [comment]
> > > In all honesty, I'm surprised no one else has mentioned it.
> 
> > 
> 
> > Isn't this entire thread about the issue that you're describing though?😅
> 
> 
> 
> No, OP wasn't able to see the lettering. I was but the color options under the settings is not there. On reddit, users were saying the same BUT were not answering what skin they were using or if they tried the default skin.

Ah, ok. Gotcha. I'll see myself out. lol

**Comment by umbrellaplug** [comment]
Update was pushed today. Closing issue. Have a good one.
