### ISSUE TITLE
Skin you used to have in the test version

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#325]
### Feature

Is there anywhere I can get the zip for the skin you used to have in the test version I liked it but now it’s gone. Thank you.

**Comment by umbrellaplug** [comment]
The skin I had was just estuary with some widgets added from the guy who does fentastic. Have you tried fentastic? If not, that would be the skin I would recommend to use instead of the one I had here. It works with umbrella. 

If you still want the other skin I had here just let me know and I'll add a zip for it here.

**Comment by umbrellaplug** [comment]
https://github.com/ivarbrandt/skin.fentastic

**Comment by Arthur1967** [comment]
Yes, I tried that one I do like the umbrella add-on better thank you for the great work you do on it I will just use that skin from his repo Have a good night.
