### ISSUE TITLE
Trakt TV Episodes Lists Not Showing Properly

### ISSUE THREAD

**Issue by cjhines7** [umbrellaplug/umbrellaplug.github.io#34]
Love the addon. For some reason, any lists I have liked that are episodes from random shows only appear as show lists, rather than episode lists. I hope that makes sense. 

An example of a list that doesn't work...
https://trakt.tv/lists/20303761

**Comment by umbrellaplug** [comment]
This is a bug in relation to the way the list is pulled. Interesting stuff Episodes are being pulled in as 'tv show' type of list causing issues. Should be set as episodes. I will look into it.

**Comment by 123Venom** [comment]
Curious where you are seeing this liked list https://trakt.tv/lists/20303761 showing up?  I decided to peak at this myself.  I "liked" the list, then forced a Trakt Sync, and it is ONLY showing up for me in `My Movies-My Liked Lists`.  That sounds strange right that it would show up in a movie list ha...but...that dudes got `Pink Panther: A Pink Christmas` MOVIE in that list...lol.  That's no longer an episode list when they mix content like that.  When I select the list it loads that one movie item only.  I then reviewed `My TV Shows-My Liked Lists` and the list does not appear so I'm not sure where you are seeing it?  This was per design back in my days as I chose NOT to support season or episode lists due to the fact I knew of no addon doing so at the time.  They are a bit of a hassle to implement but it's possible, just not something that peaked my interest enough to spend my free time on...lol.

**Comment by cjhines7** [comment]
That's a great question. I don't see the list at all now. Not sure what changed. The list does show in the Liked List Manager, but no where else.

**Comment by 123Venom** [comment]
Check `My Movies-My Liked Lists`.  It will show there and load only the one movie.  Not many addon support season/episode lists so they won't load.  It doesn't show in `My TV Shows-My Liked Lists` because there are NO shows in that list but episodes and the list does not support episode lists.  Dev would have to add the feature that was never implemented to show those as coded.

<img width="1021" alt="19d" src="https://user-images.githubusercontent.com/46383815/180628550-58be29f4-093b-4927-8a96-e99235a25b3d.PNG">

**Comment by umbrellaplug** [comment]
Episodes lists are not supported. No plans to add support for them currently. "The Promise" supports episode lists.
