### ISSUE TITLE
[BUG] Anime movie/series became empty

### ISSUE THREAD

**Issue by endlessterror** [umbrellaplug/umbrellaplug.github.io#341]
### Bug

I've got two Kodi installations (libreelec stable). Up to a week ago, the anime section contained lots of series and movies. I noticed on the pc-based install that suddenly the anime movies/series list became empty, whereas my odroid-based install still contained series/movies. At the time I thought that there was an issue with the pc install, but had no time to investigate.

Today I noticed that the anime section on odroid also became empty. 

Perhaps this is a feature and not a bug, similar to using the cocoscrapers to get sources. Looking at the umbfrella log it feels as though the query towards IMDB for "anime" returns nothing. But not a dev, so that's why I'm posting this report. 

### Expected Result

Selecting the anime section and either series or movies should display a list of movies/tv series.

### Steps To Reproduce

1. Start umbrella
2. Select Anime -> Movies (or TV Series)
3. nothing is found

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi version: 20.1.0 (Libreelec 11.0.1)

Kodi log: https://paste.kodi.tv/umodebixev
umbrella log: https://paste.kodi.tv/ipuyinujaz

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Your list was cached, that's why it just stopped working. IMDb changed their website about 15 days ago. It's been pretty widely discussed on Reddit. IMDb wants anywhere from $50,000-$150,000 a year for access to their api. Obviously, I cannot pay that for a free addon. I've done what I can to scrape the data I can from their website, but it's still hit or miss. If the problems continue, I'm just going to remove all IMDb lists from the addon.

**Comment by endlessterror** [comment]
That's ok mate, figured it might have something to do with them. Thanks for all the hours I've enjoyed anime with your plugin :)
