### ISSUE TITLE
[FEATURE] Accessing Liked Trakt lists from Private Trakt accounts

### ISSUE THREAD

**Issue by daherlihy** [umbrellaplug/umbrellaplug.github.io#349]
### Feature

I've liked a number of Lists from other Trakt users and have discovered today inside the My Liked Lists menu in the Umbrella add-on that only the lists from public Trakt accounts are displaying inside here.

Would it be possible to enable accessing the liked lists from private Trakt users also? For reference, it is possible as I've tested it in the POW addon.

**Comment by umbrellaplug** [comment]
Use POV then.

**Comment by daherlihy** [comment]
I fully appreciate you're doing your add-on and not getting anything in return, but you really didn't have to reply so pathetically.

All I did was submit a feature request here for something that is possible in other addons, hence my reference to POV.

There was nothing malicious by my reference to POV, but clearly you thought there was - that's completely on you and your inability to control yourself. All you could  have said in the end is I don't know how to do it, or I'll look into it but no promises.

**Comment by SJ1O** [comment]
> I fully appreciate you're doing your add-on and not getting anything in return, but you really didn't have to reply so pathetically.
> 
> All I did was submit a feature request here for something that is possible in other addons, hence my reference to POV.
> 
> There was nothing malicious by my reference to POV, but clearly you thought there was - that's completely on you and your inability to control yourself. All you could have said in the end is I don't know how to do it, or I'll look into it but no promises.

You posted the same issue to Peter. Pov is a fen fork so I imagine it should work in fen. Last I checked all the lists I liked showed in umbrella and fen. Without issues however I only use my own lists now so not sure if things have changed. I didn't think you can like a private list unless your given a unique URL? Anyway a better way to ask for a feature is to just ask for the feature rather then can you give me a option because it's possible on another add-on. The dev probably knows if it's possible so no need to say it works on other add-ons ect. I think most Devs would have the same response.  If pov gives you what you want you probably should just use that. Anyway hope all is well Mr umbrella. Thanks for your add-on it's appreciated and thanks for still supporting free of charge.

**Comment by adamosborne83** [comment]
> I fully appreciate you're doing your add-on and not getting anything in return, but you really didn't have to reply so pathetically.
> 
> All I did was submit a feature request here for something that is possible in other addons, hence my reference to POV.
> 
> There was nothing malicious by my reference to POV, but clearly you thought there was - that's completely on you and your inability to control yourself. All you could  have said in the end is I don't know how to do it, or I'll look into it but no promises.

And this is exactually why Devs close their GitHubs, its been closed for a good few months and opened again this week........

**Comment by umbrellaplug** [comment]
> I fully appreciate you're doing your add-on and not getting anything in return, but you really didn't have to reply so pathetically.
> 
> All I did was submit a feature request here for something that is possible in other addons, hence my reference to POV.
> 
> There was nothing malicious by my reference to POV, but clearly you thought there was - that's completely on you and your inability to control yourself. All you could have said in the end is I don't know how to do it, or I'll look into it but no promises.

USE POV THEN.
