### ISSUE TITLE
IMDB missing Next button on list and lists incomplete

### ISSUE THREAD

**Issue by hcgiub001** [umbrellaplug/umbrellaplug.github.io#368]
### Bug

This is my settings for IMDB list sorting
![Screenshot (10)](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/171574389/ca9f003d-d09c-439b-bb6d-77e7bf7741d9)

-Date Added
-Descending

Instead it's listing as Title like here
![Screenshot (11)](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/171574389/707778b7-d6ef-4695-8662-ab42514422d9)

whereas In my IMDB account the listing for Modified (it doesn't have an option for Date added)
![Screenshot (12)](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/171574389/23074998-4739-4dc0-911c-1fd376af404a)

and this is for showing listing using the Name filter (which is what I'm assuming the IMDB list sorting by Title in my settings means)
![Screenshot (13)](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/171574389/9451f3f3-0535-451c-8f20-6c41b75f8f65)

So I asked for date added but it's doing my Name filter but still the Name filter isn't correct either

It seems IMDB might have changed with how it's listing?

I also have 508 lists but it only shows 104, I expected to find a Next button but their is none.

I clicked on my Gang list and I have 559 titles like here
![Screenshot (6)](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/171574389/a9d01cc9-629d-450f-bc5c-e7547c7fcc76)

but Umbrella is only showing 24 with no next button
I asked Umbrella to 
-short sorting - date premiered 
but in IMDB I'm looking for the option of "release date"
which is the result I get here
![Screenshot (16)](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/171574389/3409727a-c95b-4e2b-aac3-f63f23810ded)

So basically it seems Their is no next button when we populate the lists and no next button inside the an actual list. and the organising of the lists is using different terminology in Umbrella compared to IMDB.
my IMDB username is 
ur158175436
and this is my lists in IMDB
https://www.imdb.com/user/ur158175436/?ref_=uspf_usr_ov

### Expected Result

I tried explaining at the top.

### Steps To Reproduce

1. Go to My Movies
2. movie lists
3. click on gang list
4.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Umbrella log
https://paste.kodi.tv/ucejiluyak

kodi log
https://paste.kodi.tv/nadequnubo

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
IMDB changed their website almost a month ago. I've rewritten umbrella to use a hard limit for imdb lists due to their removal of the next button on their pages. You can change the limit in Settings General in Umbrella, but that's not going to cover your 500+ lists. I suggest you change to something else besides imdb.

**Comment by hcgiub001** [comment]
> IMDB changed their website almost a month ago. I've rewritten umbrella to use a hard limit for imdb lists due to their removal of the next button on their pages. You can change the limit in Settings General in Umbrella, but that's not going to cover your 500+ lists. I suggest you change to something else besides imdb.

thanks for the reply. I don't think I will carry on using IMDB. but I found another addon called a4kStreaming

https://github.com/a4k-openproject/a4kStreaming

this shows a next button to find more lists. It also shows all the items in each list. though the way it does is much different and needs more work to get it setup. any chance you can have a look how he does it and use something similar? I probably need to migrate somewhere else anyway but would love to have it like a4kstreaming in umbrella

**Comment by hcgiub001** [comment]
> ![image](https://private-user-images.githubusercontent.com/69996032/339415238-59080512-dda0-49fb-b6b3-6eb93a974b88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTA5NjIsIm5iZiI6MTcxODI5MDY2MiwicGF0aCI6Ii82OTk5NjAzMi8zMzk0MTUyMzgtNTkwODA1MTItZGRhMC00OWZiLWI2YjMtNmViOTNhOTc0Yjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE0NTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OTI0YzMyZmYxMGQxZTMxYTA4MmJkNDk5ZGNjOGM5N2I5YmZmN2RjYmExN2FkYzU5NDMwZWFjMzNhMjg3NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MIxHmIEyDFZhd67zJzWOcjXzttSe-ErpEhtREVP_j28) there's the IMDb setting for your list right there right from the website

hey sorry I'm not sure what you are saying. can I change something to do what I want it to do?

**Comment by Arthur1967** [comment]
It's in the settings right on the website

**Comment by Arthur1967** [comment]
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/69996032/33ae1bd6-3b7e-4f18-8ef3-de0536d577e7)

**Comment by Arthur1967** [comment]
The upside down umbrella right up next to the + let you adjust date added, and all that stuff

**Comment by Arthur1967** [comment]
Trakt has all those settings imdb extra settings just slows this the app down for everyone

**Comment by hcgiub001** [comment]
> Trakt has all those settings imdb extra settings just slows this the app down for everyone

sorry I'm confused. I'm using corelec on odroid, not smartphone. which app have you opened? I can go into my IMDB and change the settings. that's not an issue. It doesn't remember how you organised it. it will still show as "list order"

**Comment by Arthur1967** [comment]
I give up forget it figure it out. Have a nice day like I said Trakt does the same thing.

**Comment by hcgiub001** [comment]
> I give up forget it figure it out. Have a nice day like I said Trakt does the same thing.

sorry it's me. you are right trakt is actually better. I just didn't want to lose my list, I have like 500-2000 in each list and 500+ lists...
but I found trakt rater which will import them into trakt. thanks for trying.

**Comment by Arthur1967** [comment]
It works, but not
Next up anything you do on the website will reflect in the add-on there is no next step with imdb so therefore, I don't think he could do it even if you wanted to do it. Have a good day.

**Comment by Arthur1967** [comment]
I'm glad you found a solution but just remember this Trakt uses the movie database for metadata so anything that's not in the movie database cannot be transferred. Just so you know.

**Comment by Arthur1967** [comment]
The other thing to  consider that you want to make sure of is that when you transfer it, it does not delete your list in imdb I'm just trying to help you have a good day, my friend

**Comment by hcgiub001** [comment]
> It works, but not Next up anything you do on the website will reflect in the add-on there is no next step with imdb so therefore, I don't think he could do it even if you wanted to do it. Have a good day.

I don't use smartphone. I'm still not happy with trakt. I've tried changing on the website. it doesn't save the changes. You can even try on the app on the smartphone. change it then reload it. If it does some how change it. could you please just show me. You've contributed so you know what you are doing. I've tried changing on the site. I can change on the site. Kodi does not change if you change on the site.

**Comment by umbrellaplug** [comment]
Trakt is cached. It's checked every 15 minutes by default. You can change how often it is checked and how long different lists and items are kept in cache by changing the settings for them under Cache and Trakt in the addon settings. I'm sorry, but a lot of what you have asked here is unclear to me. What exactly are you trying to do with trakt that makes you think it isn't working right.

**Comment by Arthur1967** [comment]
Takt next up works for me and I do change it on my iPhone imdb doesn't offer next up

**Comment by Arthur1967** [comment]
Umbrella he wants next up to work on imdb

**Comment by umbrellaplug** [comment]
"next up" like next episode popup?
I'm not sure that's what he's asking about. From what I get from this, he's looking for the "Next" button on the bottom of the page for his lists that contain large amounts of items. 

I had to remove the next button from imdb lists. imdb changed their website to be a different format. Now they hardcode the amount of results in the url when you go to the page and then you select a "load more" button on their pages. I have not spent the time or tried to code the addon to handle that change in design. I'm not even sure I could. I changed the code to allow you to input the number of items you want returned on that url, but it's still never going to be a page system with a next button with imdb results. Basically "next" is gone if the list or items come from imdb. You need to use the setting in Settings: General : IMDb List Amount. This setting is default 20. and the max is like 244. I believe I set it that way because 244 was the most results the new imdb format would let me call in one page without hitting "load more". That's not going to cover his issue which is lists containing over 5000+ items from imdb.

imdb has changed their website and they charge a small fortune for access to their api. I'm grabbing what I can from imdb by scraping the page, but these changes continue to make that harder and harder to do. Most other addons are not working with imdb lists at all.

I would look into importing those imdb lists into Trakt and using Trakt. That's really the simplest solution I can provide that would work with multiple addons and continue to work in the future.

**Comment by hcgiub001** [comment]
> "next up" like next episode popup? I'm not sure that's what he's asking about. From what I get from this, he's looking for the "Next" button on the bottom of the page for his lists that contain large amounts of items.
> 
> I had to remove the next button from imdb lists. imdb changed their website to be a different format. Now they hardcode the amount of results in the url when you go to the page and then you select a "load more" button on their pages. I have not spent the time or tried to code the addon to handle that change in design. I'm not even sure I could. I changed the code to allow you to input the number of items you want returned on that url, but it's still never going to be a page system with a next button with imdb results. Basically "next" is gone if the list or items come from imdb. You need to use the setting in Settings: General : IMDb List Amount. This setting is default 20. and the max is like 244. I believe I set it that way because 244 was the most results the new imdb format would let me call in one page without hitting "load more". That's not going to cover his issue which is lists containing over 5000+ items from imdb.
> 
> imdb has changed their website and they charge a small fortune for access to their api. I'm grabbing what I can from imdb by scraping the page, but these changes continue to make that harder and harder to do. Most other addons are not working with imdb lists at all.
> 
> I would look into importing those imdb lists into Trakt and using Trakt. That's really the simplest solution I can provide that would work with multiple addons and continue to work in the future.

I spent like a few hours exporting 508 lists as csv files. only to realise that trakt only allows 10 lists LMAO. So trakt isn't viable

You won't need to figure out how or spend lots of time trying to get imdb to work. Another addon
https://github.com/a4k-openproject/a4kStreaming?tab=readme-ov-file

works almost flawlessly
this is from readme
"The IMDb authentication token is the value of a cookie named at-main.
It can be obtained by opening [imdb.com](https://www.imdb.com/) in a browser, log in, then get it from:

(Chrome/Edge) DevTools > Application > Cookies
(Safari/Firefox) DevTools > Storage > Cookies"

There is a few issues with that addon which I'm trying to contact the dev but they seem to minor issues. If you can implement his code into yours, you will be the only other addon that has IMDB.
Lots of users rely on lists. I won't mind using trakt but I already have 50x more than they allow lol. I make lots of lists.

Please consider adding a4kstreaming implementation of adding imdb. his works really good

**Comment by hcgiub001** [comment]
> Takt next up works for me and I do change it on my iPhone imdb doesn't offer next up

trakt is useless for me, and pretty much to anyone that wants to create their own lists. we are only allowed to add 10 user lists. I have 508 already

**Comment by umbrellaplug** [comment]
It will never cease to amaze me how many people mention other addons in issues. As I have told many others before you that decided the best route was to bring up other addons, just use that addon then if it's working for you. I'm not going to spend a huge amount of time to reintegrate imdb because they decided to make changes. I'm not going to require users to get a token out of their browser cookies to use imdb. That's a ridiculous step most users are unlikely to do. Doing code changes because imdb made changes that few users will actually even use because of this extra step is not an idea use of my time. It's not quite as simple as just a copy and paste situation as you think when it comes to one addon vs another. That's disrespectful and minimizes the amount of work that goes into coding an addon. I understand you just want what you want and don't care about any of this, but I've tried to give better responses on issues. I closed the issue because I have no intentions of making changes to the imdb lists in the future other than maybe completely removing them as imdb has limited them so much with their changes. You may want to look into mdblists instead, but I'm not sure they might have limits as well.

Please stop replying on a closed issue. I'm getting email notifications each time, but I don't want to turn them off because someone might actually open an issue that I need to look at.
