### ISSUE TITLE
No stream available problem

### ISSUE THREAD

**Issue by tiagomiguel1994** [umbrellaplug/umbrellaplug.github.io#58]
Good Morning
I recently made a post on reddit, because I have several sources available, but at the end it says no stream available on TV Shows
I turned on the cocoscrapers debug, and I get these results.
https://paste.kodi.tv/degokaseyo
I have already installed the plugin on several devices with a clean install and still no results
thanks for your hard work

**Comment by umbrellaplug** [comment]
You're getting a lot of connection errors. What kind of device are you trying to run this on?

What Kodi version?
What's your version of scrapers and plugin?

**Comment by umbrellaplug** [comment]
Are you using kodi 19?

**Comment by tiagomiguel1994** [comment]
I'm using windows 10 with Kodi 19.4
the Plugin Version is the last one that came out yesterday (6.5.65)

**Comment by umbrellaplug** [comment]
Can you get logs from plugin and scrapers? It looks like a connection issue and I have not had any other reports of this, but I can look into your logs and see if I can help if you can attach full logs. I'd suggest closing kodi reopening with logging turned on for scrapers and umbrella and sending both logs. My development environment I build the plugin in is windows 10 and kodi 19.4 as well.

**Comment by tiagomiguel1994** [comment]
Umbrella log file
https://paste.kodi.tv/kapamefada
Kodi log file
https://paste.kodi.tv/orozoqulup
Coco log file
https://paste.kodi.tv/yopawefine

**Comment by umbrellaplug** [comment]
Perfect. I think I see the issue. Give me a few to test on my side and attempt to resolve for you.

**Comment by umbrellaplug** [comment]
Okay, I thought maybe there was an issue in a change I had made, but it doesn't seem to be the issue. Can you try installing kodi again fresh into a different directory instead of the standard program files? Install as normal, create a shortcut to kodi and on the properties of that shortcut at the end add -p to make kodi portable like this. 



That way we know it's using fresh userdata files. Please do not install the skin or any of the dependencies for the skin. Just install cocoscrapers and umbrella and see if you still get the error. I did a fresh install on my desktop with the exact version you're using of kodi and everything is running as expected. I installed. Authenticated Trakt. Added RD, then was able to play an episode you were searching for with no issues.

**Comment by tiagomiguel1994** [comment]
I think I found the problem, and the problem is not with the plugin but with alldebird, last night I bought premium on realdebrid and the problems disappeared.  
Alldebrid is inconsistent, sometimes some sources appear, other times not, and I had to revoke alldebrid because it was delaying the appearance of the page to choose the source in the real debrid which sometimes gave a timeout which made it get "no stream available"
But thanks for the effort and keep up the good work

**Comment by umbrellaplug** [comment]
Great! Have a good one.
