### ISSUE TITLE
Ability to change sort method for trakt lists in 'trending lists' and 'popular lists'.

### ISSUE THREAD

**Issue by TheGuyWhoo** [umbrellaplug/umbrellaplug.github.io#80]
As far as I can tell they are sorted by "added" by default. This makes no sense for lists like "Latest releases". I would like to sort those by release date. Is this possible at all or something you'd be likely to implement?

**Comment by umbrellaplug** [comment]
Yeah, just a quick look over the api for trakt I found this:

All list items are sorted by ascending rank. We also send X-Sort-By and X-Sort-How headers which can be used to custom sort the list in your app based on the user's preference. Values for X-Sort-By include rank, added, title, released, runtime, popularity, percentage, votes, my_rating, random, watched, and collected. Values for X-Sort-How include asc and desc.

I'd have to look at the code, but it's something I could potentially implement. I will add this on my to-do list.

**Comment by TheGuyWhoo** [comment]
Thank you, I appreciate that!

**Comment by umbrellaplug** [comment]
Okay, looked into this request today. This is already included. You can adjust the sort order of movies in setting under General and TV Shows under TV Shows tab. Some lists are going to be populated in certain orders based on the type of list it is.

Trending: Returns all lists with the most likes and comments over the last 7 days.
Popular: Returns the most popular lists. Popularity is calculated using total number of likes and comments.
Recommended: Returns the most recommended movies.

Those lists we wouldn't want to change the sort order because the sort order is the result. The first item on the list would be the most popular or trending the highest or recommended the most. I believe everything you're looking for is already in the addon so I'm going to go ahead and close this issue out. Let me know if something comes up or is unclear.

**Comment by TheGuyWhoo** [comment]
I'm not talking about the sorting of the trakt lists themselves, I'm talking about the contents of the trakt lists. I see those settings, but do they affect the contents of the trakt lists specifically? That's what I'm after.

**Comment by TheGuyWhoo** [comment]
Oh shit, just had a look and it does appear to be sorting by date released. Thanks mate, hope I didn't waste too much of your time. Btw I was wondering if I should make an issue for the multiple plex servers thing I suggested, would that be appropriate?

**Comment by umbrellaplug** [comment]
Glad you caught it before I had to make a video. :)

That would be on the scraper side and my side. I spoke with the scraper developer about this and they stated it might be possible, but they are currently busy. If changes are made to allow for it in the scrapers, I will make whatever changes are needed on my side as well.

**Comment by TheGuyWhoo** [comment]
Does the scraper have a repo?

**Comment by umbrellaplug** [comment]
It does, but the developer of the scraper doesn't check it at all. It's mainly used to pass us the scrapers. Are you having an issue or is there something you need me to bring up with them?

**Comment by TheGuyWhoo** [comment]
No, I'm not having any problems, I wanted to make an issue for my suggestion about multiple plex shares(just so I can be notified if anything happens in that regard)

**Comment by TheGuyWhoo** [comment]
No, I'm not having any problems, I wanted to make an issue for my suggestion about multiple plex shares(just so I can be notified if anything happens in that regard)

**Comment by TheGuyWhoo** [comment]
Whoops, sorry for the double if you caught it. I thought I forgot to hit comment.

**Comment by umbrellaplug** [comment]
You can open that here. It's likely I'll be the one to look at it.
