### ISSUE TITLE
Feature request - Ability to separate autoplay episodes and movies 

### ISSUE THREAD

**Issue by TechXXX** [umbrellaplug/umbrellaplug.github.io#82]
i.e. I would like to autoplay episodes but not movies. Basically I'd like the functionality Seren has ;). 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/190856783-f00c67fc-a12f-4927-9d8e-0cb9c21edc53.png">

Thanks again for helping this great addon, it's my primary addon and I love it!

**Comment by umbrellaplug** [comment]
Added to the list. :)

**Comment by TechXXX** [comment]
Great, appreciate it!

**Comment by LITUATUI** [comment]
By the way, I have the option "Source Select" enabled but it only works with movies. 

With episodes it autoplays and I can't select the source.

**Comment by umbrellaplug** [comment]
There's no option currently to have these like this so not sure how that's working. The behavior you're describing of source select for one or not the other is what he actually requested. It's not in the addon. Yet.

**Comment by LITUATUI** [comment]
![Captura de ecrã_2022-11-27_18-58-18](https://user-images.githubusercontent.com/49299328/204154424-6931d719-e293-43f2-978e-b9fe30c4cefc.jpg)

I know, I think it's a bug.

Because with the option you see in the image, I get to select the source in movies, but in episodes it autoplays.

I would like to select the source in movies and in episodes. I have this behavior in two devices, one Android tvbox and one GNU/Linux laptop.

**Comment by whambulancePilot** [comment]
@LITUATUI
If you want to be able to use SS on episodes, you cannot have the playnext popup enabled. That setting will force autoplay on episodes. It's been like that since Venom and it sounds like that's the way it behaves in Umbrella still.

**Comment by umbrellaplug** [comment]
> @LITUATUI
> 
> If you want to be able to use SS on episodes, you cannot have the playnext popup enabled. That setting will force autoplay on episodes. It's been like that since Venom and it sounds like that's the way it behaves in Umbrella still.

This is correct. It's in the works to be changed. Right now if playnext is enabled autoplay is enabled for shows automatically. The plan is to move playnext within the auto play setting where if auto play isn't on playnext isn't on by default. Then separate the settings for TV and movie auto play vs source select so that it gives each its own independent settings. 

I see ambulancepilot replying so before it even gets brought up, no I'm not planning on adding source select with auto play.

**Comment by umbrellaplug** [comment]
This is currently in testing and should be in the next update.

**Comment by TechXXX** [comment]
Awesome, appreciate it!
