### ISSUE TITLE
Plans for Umbrella/Kingpin

### ISSUE THREAD

**Issue by HashaRock** [umbrellaplug/umbrellaplug.github.io#9]
I just came across Umbrella after seeing it on Ezra's My Accounts read me and it seems like we finally have 2 good Venom forks to use. 
However, I just had a quick question of Umbrella vs Kingpin. Is Kingpin meant to be a simple fix to Venom by forking it while Umbrella is a more developed fork of Venom? I just want to make sure I use one which is good although I have both installed right now. 

Also, great work on the addon, it seems that many good changes have been made, especially to the scraper portion and the icons!

**Comment by umbrellaplug** [comment]
I'm not 100% sure as to what the plans are for Kingpin. I believe he's stated that he really just wanted to get a working version of venom that people could use from the point that venom walked away. I've seen him pull some of the more important changes over from here like importing keys instead of hard coding them, but not made any changes to the scrapers. I have no opinion of it either way. Pretty cool he setup a working version of the project so quickly for the community, if he plans to move forward with maintaining it... your guess is as good as mine. From what I've seen he's really trying.

Umbrella is planned to be further developed. It's probably not going to be a Venom clone very long... it's probably going to be more like a new fork of exodous in a long chain of exodous forks with venom's touch on it without the biblical name.

As you've noticed already the scrapers have been updated. There's more work going into those as we speak.

The icons, ehhhh I made them using font awesome in a couple of days. I'm not super proud of those and I need to go back and clean them up, but right now development has been the focus not graphics.

I am working on a few bugs that have come up. Some I seem to have inherited, some I seem to have created. :)
Examples: Epsiodes not being Marked Watched in Trakt, Repeat Notifications for Re-Authorizing Trakt.

On the feature update side, I'm looking to add a few things. Working on getting MBDlist integration done. Also looking into adding some new sources.

I keep an eye on the issues here and pop into ezra here and there and try to help him as well. I imagine if you use Ezra you're going to see me pushing something for my accounts again here soon. I'm on the fence about my accounts currently because it's been pain since the creation of all these new projects with different keys and keys not being cleared properly previously. It's not been fun to troubleshoot, but we will see where it goes. I am open to requests and such, but I'm not going to spend my every waking moment working on a free addon or anything so major rewrites of code are unlikely.

Hopefully that gives you a better idea of where things are and where they are going.

**Comment by HashaRock** [comment]
That's really great! Kodi has always been forks on forks on forks. It started with a simple video addon and ended up with so many options and evolutions. Appreciate it for putting in the work to make this add-on!

**Comment by Wilson-Fisk** [comment]
Hi just saw this here haha. Yea my original goal after I made a personal ezra fork was to make a working venom for the community because so many people were asking for one. I did that, but there are still necessary changes to be made that I am not capable of making. I am all for learning, but Umbrellaplug knows way more than I do.

With that said, I don't plan on going anywhere yet, as I know Kingpin is the more public of the 2 forks and is probably a bit more dependent on at the moment. That could (and honestly probably should) change, but we will see what the future has in store
